rev3 redesign - skeleton stage

diff --git a/firmware/Makefile b/firmware/Makefile
--- a/firmware/Makefile
+++ b/firmware/Makefile
@@ -1,125 +1,183 @@
-
-SUBDIRS = drivers
-PROJ = proj
-
-### Machine flags
+#==============================================================================
 #
-CC_CMACH	= -mmcu=msp430f5510
-CC_DMACH	= -D__MSP430F5510__
-### Build flags
+# Makefile for building MSP430 DriverLib Code examples from command line
+# environment using the GCC Open Source Compiler for MSP430
 #
+#==============================================================================
+
+PROJ:=main
+REFLIB_ROOT:=/opt/atlas430/
+#MEMORY_MODEL=LARGE
+TARGET=MSP430F5510
+
+include $(REFLIB_ROOT)/Makefile.env
+
+SUBDIRS:= 
+OBJ_DIR:=build/$(TARGET)
+
+######################################
+GCC_BIN_DIR     ?= $(GCC_DIR)/bin
+GCC_INC_DIR     ?= $(GCC_DIR)/msp430-elf/include
+######################################
+CC               = $(GCC_BIN_DIR)/msp430-elf-gcc
+GDB              = $(GCC_BIN_DIR)/msp430-elf-gdb
+######################################
+
 # -fdata-sections, -ffunction-sections and -Wl,--gc-sections -Wl,-s
 # are used for dead code elimination, see:
 # http://gcc.gnu.org/ml/gcc-help/2003-08/msg00128.html
-#
-CFLAGS		+= $(CC_CMACH) $(CC_DMACH) -Wall
-CFLAGS		+= -fno-force-addr -finline-limit=1 -fno-schedule-insns
-CFLAGS		+= -fshort-enums -Wl,-Map=output.map
-LDFLAGS		= -T /opt/msp430-gcc-support-files/include/msp430f5510.ld -L /opt/msp430-gcc-support-files/include
 
-CFLAGS_REL	+= -Os -fdata-sections -ffunction-sections -fomit-frame-pointer
-LDFLAGS_REL	+= -Wl,--gc-sections -Wl,-s
+CFLAGS       := -D__$(DEVICE)__ -mmcu=$(DEVICE) # -g -DDEPRECATED
+CFLAGS       += -Wall -Wno-switch -Wno-int-to-pointer-cast
+CFLAGS       += $(CFLAGS_EXTRA)
+#CFLAGS       += -Werror
+#CFLAGS      += -S -fverbose-asm
+#CFLAGS		 += -fno-force-addr -finline-limit=1 -fno-schedule-insns
+#CFLAGS		 += -fshort-enums -Wl,-Map=output.map
+LDFLAGS          := -T $(LDDIR).ld -L $(LIB_DIR) -L $(GCC_EXTRA_INC_DIR) -mmcu=$(DEVICE) $(HWMULT) -g -Wl,--gc-sections
+CFLAGS_REL	 += -Os -fdata-sections -ffunction-sections -fomit-frame-pointer
+LDFLAGS_REL	 += -Wl,-s
+CFLAGS_DBG	 += -O1 -ggdb
+LDFLAGS_DBG	 += 
+INCLUDES         := -I $(GCC_EXTRA_INC_DIR) -I $(GCC_INC_DIR) -I $(DRIVERLIB) -I $(GLUELIB) -I $(GLUELIB_HAL) -I $(GCC_CCS_INC_GCC_DIR) -I ./ -I .
+######################################
+DRIVERLIB_SRC    := $(wildcard $(DRIVERLIB)/*.c)
+GLUELIB_SRC      := $(wildcard $(GLUELIB)/*.c)
+GLUELIB_HAL_SRC  := $(wildcard $(GLUELIB_HAL)/*.c)
+LOCAL_SRC        := $(wildcard *.c)
+PROJ_SRC         := $(PROJ).c
+SRC              := $(PROJ_SRC) $(DRIVERLIB_SRC) $(GLUELIB_SRC) $(GLUELIB_HAL_SRC) $(LOCAL_SRC)
 
-CFLAGS_DBG	+= -O1 -ggdb
-LDFLAGS_DBG	+= -Wl,--gc-sections
+DRIVERLIB_OBJECTS = $(DRIVERLIB_SRC:$(DRIVERLIB)/%.c=$(OBJ_DIR)/%.o)
+GLUELIB_OBJECTS   = $(GLUELIB_SRC:$(GLUELIB)/%.c=$(OBJ_DIR)/%.o) $(GLUELIB_HAL_SRC:$(GLUELIB_HAL)/%.c=$(OBJ_DIR)/%.o)
+LOCAL_OBJECTS     = $(LOCAL_SRC:%.c=$(OBJ_DIR)/%.o)
 
-# linker flags and include directories
-INCLUDES	+= -I./ -Igcc/ -Idrivers/ -I/opt/msp430-gcc-support-files/include/
-### Build tools
-# 
-CC              = msp430-elf-gcc
-LD              = msp430-elf-ld
-AS              = msp430-elf-as
-AR              = msp430-elf-ar
-
-BASH := $(shell which bash || which bash)
+EXOBJECT         := $(OBJ_DIR)/$(PROJ).o
+EXOUTPUT         := $(OBJ_DIR)/$(PROJ).elf
+######################################
 
 .PHONY: all
 .PHONY: clean
 .PHONY: install
 .PHONY: config
+.PHONY: config_macros
+.PHONY: mkdir_od
+.PHONY: new_timestamps
 .PHONY: depend
+.PHONY: driverlib
 .PHONY: doc
-.PHONY: tags
-.PHONY: force
+.PHONY: cflags_update
+.PHONY: size
 
-all: depend config.h tags $(PROJ).elf
-
-#
-# Build list of sources and objects to build
-SRCS := $(wildcard *.c)
-$(foreach subdir,$(SUBDIRS), \
-	$(eval SRCS := $(SRCS) $(wildcard $(subdir)/*.c)) \
-)
-OBJS := $(patsubst %.c,%.o,$(SRCS))
-
-#
-# Dependencies rules
-depend: $(PROJ).dep
-
-$(PROJ).dep: $(SRCS)
-	@echo "Generating dependencies.."
-	@touch $@
-	@makedepend $(INCLUDES) -Y -f $@ $^ &> /dev/null
-	@rm -f $@.bak
-
-#
+ifeq ($(OS),Windows_NT)
+CFLAGS	+= $(CFLAGS_REL)
+LDFLAGS	+= $(LDFLAGS_REL)
+all: mkdir_od config.h driverlib $(EXOUTPUT)
+else
 # Append specific CFLAGS/LDFLAGS
 DEBUG := $(shell grep "^\#define CONFIG_DEBUG" config.h)
+MACROS := $(shell $(REFLIB_ROOT)/tools/extract_macros.sh -t $(TARGET) -f config.h -f i2c_config.h) -D __I2C_CONFIG_H__
+CFLAGS += $(MACROS)
 ifeq ($(DEBUG),)
-TARGET	:= RELEASE
+CTARGET	:= RELEASE
 CFLAGS	+= $(CFLAGS_REL)
 LDFLAGS	+= $(LDFLAGS_REL)
 else
-TARGET	:= DEBUG
+CTARGET	:= DEBUG
 CFLAGS	+= $(CFLAGS_DBG)
 LDFLAGS	+= $(LDFLAGS_DBG)
 endif
+all: depend version.h config.h config_macros tags driverlib new_timestamps $(EXOUTPUT) size
+endif
+
+ifeq ($(MEMORY_MODEL),LARGE)
+CFLAGS	+= -mlarge -mcode-region=lower -mdata-region=lower -D__LARGE_DATA_MODEL__ -D__LARGE_CODE_MODEL__
+LDFLAGS	+= -mlarge -mcode-region=lower
+endif
+
+config.h:
+	@echo "config.h file is missing" && false
+
+config_macros: config.h
+	@echo "active macros: $(MACROS)"
+
+$(OBJ_DIR)/%.o: $(DRIVERLIB)/%.c
+	@echo -e " * [drv] $(@F)"
+	@$(CC) $(INCLUDES) $(CFLAGS) -c $< -o $@
+
+$(OBJ_DIR)/%.o: $(GLUELIB)/%.c config.h
+	@echo -e " * [glue] $(@F)"
+	@$(CC) $(INCLUDES) $(CFLAGS) -c $< -o $@
+
+$(OBJ_DIR)/%.o: $(GLUELIB_HAL)/%.c config.h
+	@echo -e " * [glue-hal] $(@F)"
+	@$(CC) $(INCLUDES) $(CFLAGS) -c $< -o $@
+
+$(OBJ_DIR)/%.o: %.c config.h
+	@echo -e " * $(@F)"
+	@$(CC) $(INCLUDES) $(CFLAGS) -c $< -o $@
+
+$(EXOUTPUT): $(DRIVERLIB_OBJECTS) $(GLUELIB_OBJECTS) $(LOCAL_OBJECTS) $(EXOBJECT)
+	@echo -e "\n>> Building $@ as target $(CTARGET)"
+	@$(CC) $(LDFLAGS) $(DRIVERLIB_OBJECTS) $(GLUELIB_OBJECTS) $(LOCAL_OBJECTS) -o $@
+
+mkdir_od:
+	@mkdir -p $(OBJ_DIR) || echo ""
+
+clean:
+	$(RM) $(OBJ_DIR)/*.o $(OBJ_DIR)/$(PROJ).{elf,cflags,dep,hdep}
+	$(RM) -r $(OBJ_DIR)
+	$(RM) tags
+
+install: $(OBJ_DIR)/$(PROJ).elf
+	@bash $(REFLIB_ROOT)/tools/burn.sh $<
+
+envcheck:
+	@bash $(REFLIB_ROOT)/tools/check_setup.sh
 
 # rebuild if CFLAGS changed, as suggested in:
 # http://stackoverflow.com/questions/3236145/force-gnu-make-to-rebuild-objects-affected-by-compiler-definition/3237349#3237349
-$(PROJ).cflags: force
+$(OBJ_DIR)/$(PROJ).cflags: cflags_update
 	@echo "$(CFLAGS)" | cmp -s - $@ || echo "$(CFLAGS)" > $@
 
-$(OBJS): $(PROJ).cflags
-#
-# Top rules
 
-$(PROJ).elf: $(OBJS)
-	@echo -e "\n>> Building $@ as target $(TARGET)"
-	@$(CC) $(CFLAGS) $(LDFLAGS) $(INCLUDES) -o $@ $+ && size $@
+ifneq ($(OS),Windows_NT)
 
-modinit.o: modinit.c
-	@echo "CC $<"
-	@$(CC) $(CFLAGS) -Wno-implicit-function-declaration \
-		$(INCLUDES) -c $< -o $@
+version.h: $(SRC)
+	@$(REFLIB_ROOT)/tools/setver.sh
 
-%.o: %.c
-	@echo "CC $<"
-	@$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@
+$(OBJ_DIR)/$(PROJ).dep: $(SRC)
+	@echo "Generating dependencies.."
+	@mkdir -p $(OBJ_DIR)
+	@touch $@
+	@makedepend $(INCLUDES) -p "$(OBJ_DIR)/" -Y -f $@ $^ &> /dev/null
+	@sed -i "s|$(OBJ_DIR)/$(GLUELIB_HAL)/|$(OBJ_DIR)/|;s|$(OBJ_DIR)/$(GLUELIB)/|$(OBJ_DIR)/|;s|$(OBJ_DIR)/$(DRIVERLIB)/|$(OBJ_DIR)/|" $(OBJ_DIR)/main.dep
+	@grep -v ^\# $(OBJ_DIR)/$(PROJ).dep | cut -d" " -f2 | sort -u | xargs > $(OBJ_DIR)/$(PROJ).hdep
+	@echo "tags: `cat $(OBJ_DIR)/$(PROJ).hdep`" >> $(OBJ_DIR)/$(PROJ).dep
+	@rm -f $@.bak
 
-modinit.c:
-	@echo "Please do a 'make config' first!" && false
-
-config.h:
-	@echo "Please do a 'make config' first!" && false
-
-tags: $(SRCS)
+tags: $(PROJ_SRC) $(DRIVERLIB_SRC) $(GLUELIB_SRC) $(GLUELIB_HAL_SRC) $(LOCAL_SRC) $(OBJ_DIR)/$(PROJ).dep
 	@echo "Generating tags .."
-	@exuberant-ctags -R
+	@exuberant-ctags --recurse=yes ./ $(DRIVERLIB) $(GLUELIB) $(GLUELIB_HAL) $(LDDIR).h $(shell cat $(OBJ_DIR)/$(PROJ).hdep)
 
-install: $(PROJ).elf
-	@bash ~/bin/burn.sh $(PROJ).elf
-	#@mspdebug olimex-iso-mk2 "prog $<"
+new_timestamps:
+	@$(BASH) $(REFLIB_ROOT)/tools/update_rtca_now.sh
 
-clean: $(SUBDIRS)
-	@for subdir in $(SUBDIRS); do \
-		echo "Cleaning $$subdir .."; rm -f $$subdir/*.o; \
-	done
-	@rm -f *.o $(PROJ).{elf,cflags,dep} output.map
+size: $(OBJ_DIR)/$(PROJ).elf
+	@size $(OBJ_DIR)/$(PROJ).elf
 
-doc:
-	rm -rf doc/*
-	doxygen Doxyfile
-	
--include $(PROJ).dep
+debug: all
+	$(GDB) $(OBJ_DIR)/$(PROJ).elf
+
+scan-build: clean
+	@scan-build --use-cc=$(CC) --analyzer-target=msp430-elf --exclude ./driverlib/MSP430FR5xx_6xx make PARSER=scan-build
+
+cppcheck: clean
+	@cppcheck --quiet --force --enable=warning --enable=performance --enable=information --enable=missingInclude -I $(DRIVERLIB) -I $(GLUELIB) -I $(GLUELIB_HAL) -I ./ ./
+
+$(EXOBJECT): $(PROJ_SRC) $(OBJ_DIR)/$(PROJ).cflags
+	@$(CC) $(INCLUDES) $(CFLAGS) -c $< -o $@
+
+-include $(OBJ_DIR)/$(PROJ).dep
+endif
+
